import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { db } from "@/db";
import { clientAccounts } from "@/db/schema";
import { createClientUser, removeClientAccount, removeClientUser, updateClientUser } from "./actions";

export async function ClientManagement() {
  const [clients, clientUsers] = await Promise.all([db.query.clientAccounts.findMany({ orderBy: clientAccounts.name }), db.query.users.findMany({ where: (user, { eq }) => eq(user.role, "client") })]);
  return <Card><CardHeader><CardTitle className="text-base">Client users and accounts</CardTitle><CardDescription>Manage portal access, client-side roles, and account removal.</CardDescription></CardHeader><CardContent className="space-y-6">{clients.map((client) => { const members = clientUsers.filter((user) => user.clientAccountId === client.id); return <div key={client.id} className="space-y-4 rounded-md border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{client.name}</h2><p className="text-xs text-muted-foreground">{members.length} client user{members.length === 1 ? "" : "s"}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" asChild><Link href={`/agency/preview?role=client&clientId=${client.id}`}>Preview client area</Link></Button><form action={removeClientAccount}><input type="hidden" name="clientAccountId" value={client.id} /><Button type="submit" variant="destructive" size="sm">Remove client</Button></form></div></div><form action={createClientUser} className="grid gap-3 md:grid-cols-5"><input type="hidden" name="clientAccountId" value={client.id} /><Input name="name" placeholder="Name" required /><Input name="email" type="email" placeholder="Email" required /><Input name="password" type="password" minLength={8} placeholder="Temporary password" required /><Input name="clientRole" placeholder="Role" required /><Button type="submit">Add user</Button></form>{members.map((member) => <div key={member.id} className="flex flex-wrap items-center gap-3 border-t pt-3"><form action={updateClientUser} className="flex flex-1 flex-wrap items-center gap-3"><input type="hidden" name="userId" value={member.id} /><input type="hidden" name="clientAccountId" value={client.id} /><span className="w-44 text-sm"><strong>{member.name || member.email}</strong><br /><small className="text-muted-foreground">{member.email}</small></span><Input name="clientRole" defaultValue={member.clientRole || "Client user"} className="w-44" /><Select name="status" defaultValue={member.status}><SelectTrigger className="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="disabled">Disabled</SelectItem></SelectContent></Select><Button type="submit" size="sm" variant="outline">Save</Button></form><form action={removeClientUser}><input type="hidden" name="userId" value={member.id} /><input type="hidden" name="clientAccountId" value={client.id} /><Button type="submit" size="sm" variant="destructive">Remove user</Button></form></div>)}</div>; })}</CardContent></Card>;
}
